global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: [ "rabbitmq_exporter:9419" ]